MountDevPath=/dev/ttyUSB0
MountDevSpeed=19200
EncoderDevSpeed=1000000
MountReqInterval=0.1
EncoderReqInterval=0.001
SepEncoder=2
EncoderXDevPath=/dev/encoder_X0
EncoderYDevPath=/dev/encoder_Y0
EncoderSpeedInterval=0.05
RunModel=0
# telescope is in "pointing state" when coordinate error less than MaxFinePointingErr and goes to "slewing state"
#   when this error greater than MaxPointingErr
MaxPointingErr = 0.3490658504 # "pointing zone" - 20 degr
MaxFinePointingErr = 0.1745329252 # "guiding zone" - 10 degr
MaxGuidingErr = 4.8481368e-6 # "on target zone" - 1 arcsec
XPIDVP=0.9
XPIDVI=0.0005
XPIDVD=0.0
YPIDVP=0.5
YPIDVI=0.005
YPIDVD=0.
XEncZero=36627112
YEncZero=36067741
