#!/bin/bash
# start observation: open everything, turn on power etc
export http_proxy=""

echo "Turn ON hardware power"
ssh obs@192.168.70.34 ~/bin/HWpoweron
sleep 5
echo "Turn ON mount"
ssh obs@192.168.70.34 ~/bin/MOUNTpoweronoff
